apiVersion: v1
kind: Service
metadata:
  name: %DEPLOYMENT_NAME%
spec:
  type: NodePort
  ports:
  - port: 8085
    targetPort: 5000
    nodePort: 31111
    protocol: TCP
  selector:
    app: %DEPLOYMENT_NAME%
    